openapi: 3.0.0
info:
  version: 0.3.0
paths:
  /test:
    get:
      operationId: test_handler
      x-swagger-router-controller: handler
      parameters:
        - name: ids
          required: false
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        "200"
